""" SICKSense Agripollinate LiDAR Detector Version 0.3 
    Created by:    Josiah Faircloth 
    date:    11/25/2025

    Detects and tracks object clusters from SICK TiM561 LiDAR scan data. Reads LiDAR 
    log files generated by LiDAR Logger Version 0.1. Triggers a signal whenever any
    new object appears that was not present before. Requires the object to be detected
    in multiple consecutive scans before triggering, and also triggers if a known object
    moves significantly from its original position. Includes a cooldown period between 
    triggers to avoid excessive alerts, and stores "tracked" objects separately.
"""

import json
import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN

# -------------------------------
# Configuration Parameters
# -------------------------------
SCAN_FILE = "lidar_log_12-02-2025_12.50.17.jsonl"  # LiDAR data file 
EPS = 0.25        # DBSCAN cluster distance threshold (meters) - minimum distance between points in a cluster
MIN_SAMPLES = 3   # minimum points per cluster
NEW_OBJ_DIST = 0.3  # meters: if a centroid is this far from all previous, treat as new
OBJECT_MEMORY_TIME = 1  # seconds: remember objects for this long after last seen
MIN_DETECTIONS = 4  # number of consecutive scans object must appear before triggering
TRIGGER_COOLDOWN = 2    # seconds: minimum time that must pass between triggers
ESTABLISHED_THRESHOLD = 2.0  # seconds to be considered "established"
DISPLAY = True

# -------------------------------
# Event Trigger Function
# -------------------------------
def on_new_object_detected(centroid, timestamp, last_trigger, count):
    """Called whenever a new cluster appears that wasn't present before."""

    #Check if the cooldown period has passed
    if last_trigger is None or timestamp - last_trigger >= TRIGGER_COOLDOWN:
        print(f"[ALERT] New object detected at {centroid} at {timestamp:.2f}") # Will be replaced with image capture
        return timestamp, count + 1
    else:
        return last_trigger, count

# -------------------------------
# Helper Functions
# -------------------------------
def polar_to_cartesian(ranges):
    """Convert polar ranges to (x, y) coordinates"""
    angles = np.linspace(-45, 225, len(ranges))
    x = ranges * np.cos(np.deg2rad(angles))
    y = ranges * np.sin(np.deg2rad(angles))
    return np.column_stack((x, y)) # (N, 2) array of (x, y) points

def detect_objects(points):
    """Cluster points using DBSCAN and return cluster centroids"""
    points = points[~np.isnan(points).any(axis=1)] # Remove NaN points
    if len(points) < MIN_SAMPLES: # Exit if not enough points to form clusters
        return []
    db = DBSCAN(eps=EPS, min_samples=MIN_SAMPLES).fit(points)
    labels = db.labels_ # Cluster labels for each point
    centroids = []
    for lbl in np.unique(labels):
        if lbl == -1:  # remove noise
            continue
        cluster = points[labels == lbl]
        centroids.append(np.mean(cluster, axis=0)) # Compute centroid of cluster
    return np.array(centroids) # (M, 2) array of centroids


class ObjectTracker:
    """Tracks known objects over time with memory persistence and confirmation"""
    def __init__(self, memory_time=2.0, established_threshold=2.0, distance_threshold=0.4, min_detections=3):
        self.candidate_objects = []  # List of (centroid, first_seen_time, detection_count)
        self.tracking_objects = {}  # {object_id: {'position': np.array, 'init_pos': np.array,'first_seen': float,'last_seen': float, 'status': str}}
        self.next_object_id = 0
        self.established_threshold = established_threshold 
        self.memory_time = memory_time
        self.distance_threshold = distance_threshold
        self.min_detections = min_detections
        self.first_scan = True
    
    def update(self, current_centroids, current_time):
        """Update tracker with new centroids, return list of NEW objects"""
        # On first scan, add all objects without triggering
        if self.first_scan:
            for centroid in current_centroids:
                # Add to tracking objects as "established"
                obj_id = self.next_object_id
                self.next_object_id += 1
                self.tracking_objects[obj_id] = {
                    'position': centroid.copy(),
                    'init_pos': centroid.copy(),
                    'first_seen': current_time,
                    'last_seen': current_time,
                    'status': 'established'
                }
            self.first_scan = False
            return np.array([]).reshape(0, 2), self.tracking_objects.copy()  # No new objects on first scan
        
        # Clean up old tracking objects
        ids_to_remove = []
        for obj_id, obj_data in self.tracking_objects.items():
            if current_time - obj_data['last_seen'] > self.memory_time:
                ids_to_remove.append(obj_id)
        for obj_id in ids_to_remove:
            del self.tracking_objects[obj_id]

        # Clean up old candidates
        self.candidate_objects = [(pos, first_t, count) for pos, first_t, count in self.candidate_objects 
                                  if current_time - first_t < self.memory_time]
        
        new_objects = []
        matched_candidates = set()
        
        for centroid in current_centroids:
            matched = False
            
            # Check if matches an existing tracking object
            for obj_id, obj_data in self.tracking_objects.items():
                dist = np.linalg.norm(centroid - obj_data['position'])
                if dist < self.distance_threshold:
                    # Update tracking object
                    obj_data['position'] = centroid.copy()
                    obj_data['last_seen'] = current_time
                    
                    # Update status based on time tracked
                    if obj_data['status'] == 'established':
                        if np.linalg.norm(centroid - obj_data['init_pos']) > self.distance_threshold:
                            new_objects.append(centroid)
                            obj_data['status'] = 'tracking' # Downgrade to tracking if moved significantly
                    else:
                        time_tracked = current_time - obj_data['first_seen']
                        if time_tracked >= self.established_threshold:
                            obj_data['status'] = 'established'
                        else:
                            obj_data['status'] = 'tracking'
                    
                    matched = True
                    break
            
            if matched:
                continue
            
            # Check if matches a candidate object
            for i, (cand_pos, first_t, count) in enumerate(self.candidate_objects):
                dist = np.linalg.norm(centroid - cand_pos)
                if dist < self.distance_threshold:
                    # Increment detection count
                    new_count = count + 1
                    if new_count >= self.min_detections:
                        # Promote and trigger
                        new_objects.append(centroid)

                        # Add to tracking objects as "new"
                        obj_id = self.next_object_id
                        self.next_object_id += 1
                        self.tracking_objects[obj_id] = {
                            'position': centroid.copy(),
                            'init_pos': centroid.copy(),
                            'first_seen': current_time,
                            'last_seen': current_time,
                            'status': 'new'
                        }
                        #self.confirmed_objects.append((current_time, centroid))
                        matched_candidates.add(i)
                    else:
                        # Update candidate
                        self.candidate_objects[i] = (centroid, first_t, new_count)
                        matched_candidates.add(i)
                    matched = True
                    break
            
            if not matched:
                # New candidate object (first detection)
                self.candidate_objects.append((centroid, current_time, 1))
        
        # Remove matched candidates that were promoted
        self.candidate_objects = [c for i, c in enumerate(self.candidate_objects) 
                                  if i not in matched_candidates or c[2] < self.min_detections]
        
        
        # Return new objects and tracking status dictionary
        if new_objects:
            return np.array(new_objects).reshape(-1, 2), self.tracking_objects.copy()
        else:
            return np.array([]).reshape(0, 2), self.tracking_objects.copy()
        

# -------------------------------
# Main Loop
# -------------------------------
def main():
    #initialize values
    tracker = ObjectTracker(
        memory_time=OBJECT_MEMORY_TIME, 
        established_threshold=ESTABLISHED_THRESHOLD,
        distance_threshold=NEW_OBJ_DIST,
        min_detections=MIN_DETECTIONS,
    )
    plt.ion()
    fig, ax = plt.subplots(figsize=(10, 10))
    object_count = 0
    last_trigger_time = None

    #Open LiDAR log file and process each scan
    with open(SCAN_FILE, 'r') as f:
        for line in f:
            try:
                # Read and preprocess line
                scan = json.loads(line)
                ranges = np.array(scan["ranges"])
                ranges[(ranges < 0.005) | (ranges > 10)] = np.nan

                #Helper functions
                points = polar_to_cartesian(ranges)
                centroids = detect_objects(points)
                new_objects, tracking_info = tracker.update(centroids, scan["timestamp"])

                # Trigger event if new objects appear
                for c in new_objects:
                    last_trigger_time, object_count = on_new_object_detected(c, scan["timestamp"], last_trigger_time, object_count)

                # Visualize
                if DISPLAY:
                    ax.clear()
                    ax.scatter(points[:, 0], points[:, 1], s=5, c='gray', label='Scan points')

                    # Separate tracking objects by status
                    new_objs = []
                    tracking_objs = []
                    established_objs = []
                    
                    for obj_id, obj_data in tracking_info.items():
                        pos = obj_data['position']
                        status = obj_data['status']
                        if status == 'new':
                            new_objs.append(pos)
                        elif status == 'tracking':
                            tracking_objs.append(pos)
                        else:  # established
                            established_objs.append(pos)

                    # Plot each category
                    if established_objs:
                        established_objs = np.array(established_objs)
                        ax.scatter(established_objs[:, 0], established_objs[:, 1], c='green', s=40, marker='o', label='Established')
                    
                    if tracking_objs:
                        tracking_objs = np.array(tracking_objs)
                        ax.scatter(tracking_objs[:, 0], tracking_objs[:, 1], c='yellow', s=50, marker='s', label='Tracking')
                    
                    if new_objs:
                        new_objs = np.array(new_objs)
                        ax.scatter(new_objs[:, 0], new_objs[:, 1], c='red', s=80, marker='*', label='NEW')
                        
                    ax.set_xlim(-7.5, 7.5)
                    ax.set_ylim(-7.5, 7.5)
                    ax.set_title("LiDAR Object Detection")
                    ax.legend(loc='upper right')
                    ax.set_aspect('equal')
                    plt.pause(0.01)
                #time.sleep(0.05)
            except json.JSONDecodeError:
                continue

    plt.ioff()
    plt.show()
    print(f"Total objects detected: {object_count}")

if __name__ == "__main__":
    main()